image: node:20

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

cache:
  paths:
    - node_modules/

stages:
  - install
  - build
  - dockerize
  - deploy

before_script:
  - npm ci

install_dependencies:
  stage: install
  script:
    - echo "Dependencies installed"

build_app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .next
      - public
      - package.json
      - next.config.js
  only:
    - develop

build_docker:
  stage: dockerize
  script:
    - docker build -t idrama-web:${CI_COMMIT_SHORT_SHA} .
  only:
    - develop

deploy:
  stage: deploy
  script:
    - echo "Deploy step: only run on self-hosted runner"
    # - ssh user@server "docker stop idrama-web && docker rm idrama-web"
    # - ssh user@server "docker run -d --name idrama-web -p 3000:3000 idrama-web:${CI_COMMIT_SHORT_SHA}"
  only:
    - main
